# Resources set on the OSC
executor: slurm
jobs: 10
latency-wait: 30
scheduler: greedy
default-resources:
    slurm_account: "pas2694"

set-resources:
    cellranger_arc_count:
        mem_mb: 16000
        runtime: 600
    run_droplet_utils:
        mem_mb: 32000
        runtime: 60
    filter_vcf:
        mem_mb: 16000
        runtime: 60
    demuxlet_gex:
        mem_mb: 32000
        runtime: 4320
    demuxlet_atac: 
        mem_mb: 32000
        runtime: 4320
    