# Resources set on the OSC
executor: slurm
jobs: 10
default-resources:
    slurm_account: "pas2694"

set-resources:
    cellranger_arc_count:
        mem_mb: 128000
        runtime: 540
        slurm_extra: "'--nice=100'"
        cpus_per_task: 20
    run_droplet_utils:
        mem_mb: 20000
        runtime: 60
    filter_vcf:
        mem_mb: 10000
        runtime: 60
    demuxlet_gex:
        mem_mb: 20000
        runtime: 4320
    demuxlet_atac: 
        mem_mb: 20000
        runtime: 4320
    