include: "rules/00_cellranger_arc.smk"
include: "rules/01_filter_vcf.smk"
include: "rules/02_demuxlet_gex.smk"
include: "rules/03_demuxlet_atac.smk"

onstart:
    print("★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★")
    print("★★★★★  This is the align & demultiplex pipeline for multiomics data   ★★★★★")
    print("★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★")

all_input_list = [
    rules.cellranger_arc_all.input,
    rules.demuxlet_gex_all.input,
    rules.demuxlet_atac_all.input
]

if(not(config.get("skip_vcf_filter", False))):
    all_input_list.append([rules.filter_all.input])

rule all:
    input:
        all_input_list
    default_target: True